### ISSUE TITLE
Bug with `ror`?

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/aig#1]
In the definition of `ror`, there is a call to `rolC`, which I very much suspect is a typo/bug.

@brianhuffman, can you take a look: I'm not confident I understand the rotation circuits you've built.

**Comment by brianhuffman** [comment]
Yes, that is definitely a cut-and-paste error. The `rolC` should be `rorC`.

Apparently the reason I never noticed this bug in `ror` is that the `saw-core-aig` package doesn't use it, so rotates still work correctly in SAW. I should change `saw-core-aig` to use the rotate/shift functions from `aig` and remove the duplicate code.
